// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Company struct {
	ID              int32          `json:"id"`
	Name            string         `json:"name"`
	Domain          *string        `json:"domain"`
	Industry        *string        `json:"industry"`
	Street          *string        `json:"street"`
	City            *string        `json:"city"`
	State           *string        `json:"state"`
	Country         *string        `json:"country"`
	PostalCode      *string        `json:"postal_code"`
	ParentCompanyID *int32         `json:"parent_company_id"`
	CustomFields    []byte         `json:"custom_fields"`
	CompanySize     *string        `json:"company_size"`
	EmployeeCount   *int32         `json:"employee_count"`
	AnnualRevenue   pgtype.Numeric `json:"annual_revenue"`
	RevenueCurrency *string        `json:"revenue_currency"`
	CreatedBy       int32          `json:"created_by"`
	UpdatedBy       *int32         `json:"updated_by"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
	DeletedAt       sql.NullTime   `json:"deleted_at"`
}

type Contact struct {
	ID           int32        `json:"id"`
	FirstName    string       `json:"first_name"`
	LastName     string       `json:"last_name"`
	Email        *string      `json:"email"`
	Phone        *string      `json:"phone"`
	CompanyID    *int32       `json:"company_id"`
	CustomFields []byte       `json:"custom_fields"`
	DeletedAt    sql.NullTime `json:"deleted_at"`
	CreatedBy    int32        `json:"created_by"`
	UpdatedBy    *int32       `json:"updated_by"`
	CreatedAt    time.Time    `json:"created_at"`
	UpdatedAt    time.Time    `json:"updated_at"`
}
