// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
)

type Querier interface {
	CountContacts(ctx context.Context) (int64, error)
	CountContactsByCompany(ctx context.Context, companyID *int32) (int64, error)
	CreateCompany(ctx context.Context, arg CreateCompanyParams) (Company, error)
	CreateContact(ctx context.Context, arg CreateContactParams) (Contact, error)
	FilterContacts(ctx context.Context, arg FilterContactsParams) ([]FilterContactsRow, error)
	GetCompaniesByIndustry(ctx context.Context, industry *string) ([]Company, error)
	GetCompaniesByRevenue(ctx context.Context, arg GetCompaniesByRevenueParams) ([]GetCompaniesByRevenueRow, error)
	GetCompanyByDomain(ctx context.Context, domain *string) (GetCompanyByDomainRow, error)
	GetCompanyByID(ctx context.Context, id int32) (Company, error)
	GetCompanyHierarchy(ctx context.Context, id int32) ([]GetCompanyHierarchyRow, error)
	GetContactByEmail(ctx context.Context, email *string) (GetContactByEmailRow, error)
	GetContactByID(ctx context.Context, id int32) (GetContactByIDRow, error)
	GetContactsByDomain(ctx context.Context, dollar_1 *string) ([]GetContactsByDomainRow, error)
	GetSubsidiaries(ctx context.Context, parentCompanyID *int32) ([]Company, error)
	ListCompanies(ctx context.Context, arg ListCompaniesParams) ([]Company, error)
	ListContacts(ctx context.Context, arg ListContactsParams) ([]ListContactsRow, error)
	ListContactsByCompany(ctx context.Context, companyID *int32) ([]Contact, error)
	SearchCompaniesByCustomField(ctx context.Context, arg SearchCompaniesByCustomFieldParams) ([]Company, error)
	SearchCompaniesByName(ctx context.Context, arg SearchCompaniesByNameParams) ([]Company, error)
	SearchContactsByCustomField(ctx context.Context, arg SearchContactsByCustomFieldParams) ([]Contact, error)
	SearchContactsFullText(ctx context.Context, arg SearchContactsFullTextParams) ([]SearchContactsFullTextRow, error)
	SoftDeleteCompany(ctx context.Context, arg SoftDeleteCompanyParams) error
	SoftDeleteContact(ctx context.Context, arg SoftDeleteContactParams) error
	UpdateCompany(ctx context.Context, arg UpdateCompanyParams) (Company, error)
	UpdateCompanyCustomFields(ctx context.Context, arg UpdateCompanyCustomFieldsParams) (Company, error)
	UpdateContact(ctx context.Context, arg UpdateContactParams) (Contact, error)
	UpdateContactCustomFields(ctx context.Context, arg UpdateContactCustomFieldsParams) (Contact, error)
}

var _ Querier = (*Queries)(nil)
