// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
)

type Querier interface {
	CheckEmailExists(ctx context.Context, email string) (bool, error)
	CleanupExpiredTokens(ctx context.Context) error
	CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) (CreatePasswordResetTokenRow, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	DeactivateUser(ctx context.Context, arg DeactivateUserParams) error
	GetPasswordResetToken(ctx context.Context, token string) (GetPasswordResetTokenRow, error)
	GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error)
	GetUserByID(ctx context.Context, id int32) (GetUserByIDRow, error)
	GetUserForAuth(ctx context.Context, email string) (GetUserForAuthRow, error)
	GetUserPasswordResetTokens(ctx context.Context, userID *int32) ([]GetUserPasswordResetTokensRow, error)
	ListActiveUsers(ctx context.Context) ([]ListActiveUsersRow, error)
	ListUsersByRole(ctx context.Context, role string) ([]ListUsersByRoleRow, error)
	MarkPasswordResetTokenUsed(ctx context.Context, token string) error
	SoftDeleteUser(ctx context.Context, arg SoftDeleteUserParams) error
	UpdateUserLastLogin(ctx context.Context, id int32) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpdateUserPermissions(ctx context.Context, arg UpdateUserPermissionsParams) error
	UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) error
	VerifyUserEmail(ctx context.Context, arg VerifyUserEmailParams) error
}

var _ Querier = (*Queries)(nil)
