namespace: mtenant
registry: localhost:5000

authService:
  enabled: true
  replicas: 1
  tag: latest

tenantService:
  enabled: true
  replicas: 1
  tag: latest

contactService:
  enabled: true
  replicas: 1
  tag: latest

dealService:
  enabled: true
  replicas: 1
  tag: latest

communicationService:
  enabled: true
  replicas: 1
  tag: latest

postgres:
  enabled: true
  labels:
    deployment:
    pvc:
    secret:
    service:
  image: postgres
  tag: 15
  credentials:
    username:
    password:
    database:
  storage:
    size:
    storageClass:

nats:
  enabled: true
  labels:
    deployment:
    service:
  image: nats
  tag: latest

redis:
  enabled: true
  labels:
    deployment:
    service:
  image: redis
  tag: 7.0-alpine
  config:
    maxMemoryPolicy:
    maxMemory:
