{{ include "mtenant.service.deployment" (dict "root" . "key" "authService" "name" "auth-service" "port" 8080) }}
---
{{ include "mtenant.service.service" (dict "root" . "key" "authService" "name" "auth-service" "port" 8080) }}
