{{ include "mtenant.service.deployment" (dict "root" . "key" "communicationService" "name" "communication-service" "port" 8084) }}
---
{{ include "mtenant.service.service" (dict "root" . "key" "communicationService" "name" "communication-service" "port" 8084) }}
