{{ include "mtenant.service.deployment" (dict "root" . "key" "contactService" "name" "contact-service" "port" 8082) }}
---
{{ include "mtenant.service.service" (dict "root" . "key" "contactService" "name" "contact-service" "port" 8082) }}
