apiVersion: v1
kind: Service
metadata:
  name: nats-service
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "mtenant.labels.nats" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - name: client
    port: 4222
  - name: monitoring
    port: 8222
  selector:
    app: nats
