apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mtenant-pvc 
  namespace: {{ .Values.namespace }}
  labels:
    {{- range $key, $val := .Values.postgres.labels.pvc }}
    {{ $key }}: {{ $val }}
    {{- end }}
spec:
  storageClassName: {{ .Values.postgres.storage.storageClass }}
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgres.storage.size }}