apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mtenant-pvc
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "mtenant.labels.postgres" . | nindent 4 }}
spec:
  storageClassName: {{ .Values.postgres.storage.storageClass }}
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgres.storage.size }}
