apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: mtenant
  labels:
    {{- range $key, $val := .Values.postgres.labels.pvc }}
    {{ $key }}: {{ $val }}
    {{- end }}
type: Opaque
data:
  username: {{ .Values.postgres.credentials.username | b64enc }}
  password: {{ .Values.postgres.credentials.password | b64enc }}
  database: {{ .Values.postgres.credentials.database | b64enc }}