{{- if .Values.redis.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  namespace: {{ .Values.namespace }}
  labels:
    {{- range $key, $val := .Values.redis.labels.deployment }}
    {{ $key }}: {{ $val }}
    {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: {{ .Values.redis.image }}:{{ .Values.redis.tag }}
        ports:
        - containerPort: 6379
        args:
        - "--maxmemory-policy"
        - "{{ .Values.redis.config.maxMemoryPolicy }}"
        - "--maxmemory"
        - "{{ .Values.redis.config.maxMemory }}"
{{- end }}