{{ include "mtenant.service.deployment" (dict "root" . "key" "tenantService" "name" "tenant-service" "port" 8081) }}
---
{{ include "mtenant.service.service" (dict "root" . "key" "tenantService" "name" "tenant-service" "port" 8081) }}
