// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Company struct {
	ID              int32              `json:"id"`
	Name            string             `json:"name"`
	Domain          *string            `json:"domain"`
	Industry        *string            `json:"industry"`
	Street          *string            `json:"street"`
	City            *string            `json:"city"`
	State           *string            `json:"state"`
	Country         *string            `json:"country"`
	PostalCode      *string            `json:"postal_code"`
	ParentCompanyID *int32             `json:"parent_company_id"`
	CustomFields    []byte             `json:"custom_fields"`
	CompanySize     *string            `json:"company_size"`
	EmployeeCount   *int32             `json:"employee_count"`
	AnnualRevenue   pgtype.Numeric     `json:"annual_revenue"`
	RevenueCurrency *string            `json:"revenue_currency"`
	CreatedBy       int32              `json:"created_by"`
	UpdatedBy       *int32             `json:"updated_by"`
	CreatedAt       time.Time          `json:"created_at"`
	UpdatedAt       time.Time          `json:"updated_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
}

type Contact struct {
	ID           int32              `json:"id"`
	FirstName    string             `json:"first_name"`
	LastName     string             `json:"last_name"`
	Email        *string            `json:"email"`
	Phone        *string            `json:"phone"`
	CompanyID    *int32             `json:"company_id"`
	CustomFields []byte             `json:"custom_fields"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
	CreatedBy    int32              `json:"created_by"`
	UpdatedBy    *int32             `json:"updated_by"`
	CreatedAt    time.Time          `json:"created_at"`
	UpdatedAt    time.Time          `json:"updated_at"`
}

type Deal struct {
	ID                int32          `json:"id"`
	Title             string         `json:"title"`
	Description       *string        `json:"description"`
	Value             pgtype.Numeric `json:"value"`
	Currency          *string        `json:"currency"`
	Stage             string         `json:"stage"`
	Probability       *int32         `json:"probability"`
	ExpectedCloseDate sql.NullTime   `json:"expected_close_date"`
	ActualCloseDate   sql.NullTime   `json:"actual_close_date"`
	OwnerID           *int32         `json:"owner_id"`
	CompanyID         *int32         `json:"company_id"`
	PrimaryContactID  *int32         `json:"primary_contact_id"`
	Source            *string        `json:"source"`
	CloseReason       *string        `json:"close_reason"`
	CustomFields      []byte         `json:"custom_fields"`
	CreatedAt         time.Time      `json:"created_at"`
	UpdatedAt         time.Time      `json:"updated_at"`
	CreatedBy         *int32         `json:"created_by"`
}

type DealContact struct {
	DealID    int32     `json:"deal_id"`
	ContactID int32     `json:"contact_id"`
	Role      *string   `json:"role"`
	CreatedAt time.Time `json:"created_at"`
}

type User struct {
	ID            int32              `json:"id"`
	Email         string             `json:"email"`
	PasswordHash  string             `json:"password_hash"`
	FirstName     string             `json:"first_name"`
	LastName      string             `json:"last_name"`
	Role          string             `json:"role"`
	Permissions   []byte             `json:"permissions"`
	Active        *bool              `json:"active"`
	EmailVerified *bool              `json:"email_verified"`
	LastLogin     pgtype.Timestamptz `json:"last_login"`
	CreatedBy     *int32             `json:"created_by"`
	UpdatedBy     *int32             `json:"updated_by"`
	CreatedAt     time.Time          `json:"created_at"`
	UpdatedAt     time.Time          `json:"updated_at"`
	DeletedAt     pgtype.Timestamptz `json:"deleted_at"`
}
