// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	AddDealContact(ctx context.Context, arg AddDealContactParams) (DealContact, error)
	CloseDeal(ctx context.Context, arg CloseDealParams) (Deal, error)
	CountDeals(ctx context.Context) (int64, error)
	CreateDeal(ctx context.Context, arg CreateDealParams) (Deal, error)
	DeleteDeal(ctx context.Context, id int32) (int64, error)
	GetContactDeals(ctx context.Context, contactID int32) ([]GetContactDealsRow, error)
	GetDealByID(ctx context.Context, id int32) (GetDealByIDRow, error)
	GetDealContacts(ctx context.Context, dealID int32) ([]GetDealContactsRow, error)
	GetDealsByOwner(ctx context.Context, ownerID *int32) ([]Deal, error)
	GetDealsByStage(ctx context.Context) ([]GetDealsByStageRow, error)
	GetMonthlyForecast(ctx context.Context) ([]GetMonthlyForecastRow, error)
	GetSalesRepPerformance(ctx context.Context, actualCloseDate sql.NullTime) ([]GetSalesRepPerformanceRow, error)
	ListDeals(ctx context.Context, arg ListDealsParams) ([]ListDealsRow, error)
	RemoveDealContact(ctx context.Context, arg RemoveDealContactParams) error
	UpdateDeal(ctx context.Context, arg UpdateDealParams) (Deal, error)
}

var _ Querier = (*Queries)(nil)
