// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
	"encoding/json"
	"time"
)

type Invitation struct {
	ID         int32           `json:"id"`
	TenantID   *int32          `json:"tenant_id"`
	Email      string          `json:"email"`
	Role       string          `json:"role"`
	Token      string          `json:"token"`
	ExpiresAt  time.Time       `json:"expires_at"`
	AcceptedAt sql.NullTime    `json:"accepted_at"`
	InvitedBy  *int32          `json:"invited_by"`
	Metadata   json.RawMessage `json:"metadata"`
	CreatedAt  time.Time       `json:"created_at"`
}

type Tenant struct {
	ID         int32     `json:"id"`
	Name       string    `json:"name"`
	Subdomain  string    `json:"subdomain"`
	SchemaName string    `json:"schema_name"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}
