// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
)

type Querier interface {
	AcceptInvitation(ctx context.Context, token string) error
	CheckPendingInvitation(ctx context.Context, arg CheckPendingInvitationParams) (bool, error)
	CheckSchemaNameExists(ctx context.Context, schemaName string) (bool, error)
	CheckSubdomainExists(ctx context.Context, subdomain string) (bool, error)
	CleanupExpiredInvitations(ctx context.Context) error
	CountTenants(ctx context.Context) (int64, error)
	CreateInvitation(ctx context.Context, arg CreateInvitationParams) (CreateInvitationRow, error)
	CreateTenant(ctx context.Context, arg CreateTenantParams) (CreateTenantRow, error)
	GetInvitationByToken(ctx context.Context, token string) (GetInvitationByTokenRow, error)
	GetInvitationsByEmail(ctx context.Context, email string) ([]GetInvitationsByEmailRow, error)
	GetRecentTenants(ctx context.Context, limit int32) ([]GetRecentTenantsRow, error)
	GetSchemaNameBySubdomain(ctx context.Context, subdomain string) (string, error)
	GetTenantByID(ctx context.Context, id string) (Tenant, error)
	GetTenantBySchemaName(ctx context.Context, schemaName string) (Tenant, error)
	GetTenantBySubdomain(ctx context.Context, subdomain string) (Tenant, error)
	ListAllTenants(ctx context.Context) ([]ListAllTenantsRow, error)
	ListPendingInvitations(ctx context.Context) ([]ListPendingInvitationsRow, error)
	ListTenantInvitations(ctx context.Context, tenantID *string) ([]ListTenantInvitationsRow, error)
	RevokeInvitation(ctx context.Context, arg RevokeInvitationParams) error
	UpdateTenantName(ctx context.Context, arg UpdateTenantNameParams) error
}

var _ Querier = (*Queries)(nil)
